apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-sender
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q=
  RABBIT_PASSWORD: Z3Vlc3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-sender
  labels:
    app: rabbitmq-sender
spec:
  selector:
    matchLabels:
      app: rabbitmq-sender
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-sender
    spec:
      containers:
        - name: rabbitmq-sender
          image: deliodiaz/sender:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBIT_HOST
              value: 'rabbitmq-0.rabbitmq.rabbits.svc.cluster.local'
            - name: RABBIT_PORT
              value: '5672'
            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-sender
                  key: RABBIT_USERNAME
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-sender
                  key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-sender
  labels:
    app: rabbitmq-sender
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq-sender
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
